mixed-port: 7890
allow-lan: true
mode: rule
log-level: info

proxies:
  - name: MY-RELAY
    type: vless
    server: 205.186.67.61
    port: 20000
    uuid: ac8cc211-fb3e-4ccc-912d-5d3f3190e4c7
    network: tcp
    tls: true
    servername: www.cloudflare.com
    reality-opts:
      public-key: FFikQX11fcy3vvXzkRa_8vb9-08S6yHGK5PH5mgcumA
      short-id: a1b2c3d4

proxy-groups:
  - name: 🚀 Proxy
    type: select
    proxies:
      - MY-RELAY

rules:
  - MATCH,🚀 Proxy
