mixed-port: 7890
allow-lan: true
mode: rule
log-level: info

proxies:
  - name: MY-Relay-MY
    type: vless
    server: 205.186.67.61
    port: 20000
    uuid: ac8cc211-fb3e-4ccc-912d-5d3f3190e4c7
    network: tcp
    udp: false
    tls: true
    servername: www.microsoft.com
    client-fingerprint: chrome
    reality-opts:
      public-key: FFikQX11fcy3vvXzkRa_8vb9-08S6yHGK5PH5mgcumA
      short-id: a1b2c3d4

  - name: US-Relay-LA
    type: vless
    server: 166.88.209.29
    port: 20000
    uuid: e58af7e4-4f5d-4d67-8295-e89a42ec34be
    network: tcp
    udp: false
    tls: true
    servername: www.microsoft.com
    client-fingerprint: chrome
    reality-opts:
      public-key: 38jHwbilbDPOjcfk6BM8QM7PJrOOiQerViz8lgYlzEg
      short-id: a1b2c3d4

proxy-groups:
  - name: Bodly
    type: select
    proxies:
      - MY-Relay-MY
      - US-Relay-LA

rules:
  - MATCH,Bodly
