mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
ipv6: false

unified-delay: true
tcp-concurrent: true
find-process-mode: strict

geodata-mode: true
geo-auto-update: true
geo-update-interval: 24

profile:
  store-selected: true
  store-fake-ip: true

tun:
  enable: true
  stack: mixed
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  proxy-server-nameserver:
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query

proxies:
  - name: MY-Relay-MY
    type: vless
    server: 205.186.67.61
    port: 20000
    uuid: ac8cc211-fb3e-4ccc-912d-5d3f3190e4c7
    network: tcp
    tls: true
    servername: www.microsoft.com
    client-fingerprint: chrome
    reality-opts:
      public-key: FFikQX11fcy3vvXzkRa_8vb9-08S6yHGK5PH5mgcumA
      short-id: a1b2c3d4

  - name: US-Relay-LA
    type: vless
    server: 166.88.209.29
    port: 20000
    uuid: e58af7e4-4f5d-4d67-8295-e89a42ec34be
    network: tcp
    tls: true
    servername: www.microsoft.com
    client-fingerprint: chrome
    reality-opts:
      public-key: jaL3D2sVwU-RU4mKJzs-VtL8D6u5UAZOghKofhpIJjM
      short-id: a1b2c3d4

proxy-groups:
  - name: Bodly
    type: select
    proxies:
      - Auto
      - US-Relay-LA
      - MY-Relay-MY
      - DIRECT

  - name: Auto
    type: url-test
    proxies:
      - US-Relay-LA
      - MY-Relay-MY
    url: http://www.gstatic.com/generate_204
    interval: 300

  - name: TikTok
    type: select
    proxies:
      - US-Relay-LA
      - Bodly
      - MY-Relay-MY

rules:
  # 国内直连
  - GEOIP,CN,DIRECT

  # TikTok 强制美国
  - DOMAIN-SUFFIX,tiktok.com,TikTok
  - DOMAIN-SUFFIX,tiktokv.com,TikTok

  # 默认走代理
  - MATCH,Bodly
